### ISSUE TITLE
FRAG_ENV variables configuration.

### ISSUE THREAD

**Issue by RayFoss** [fragmenta/fragmenta-cms#10]
Where does one set the fragmenta environment variables?

I see one mention of it in 
```
github.com/fragmenta/server/server.go:41:	if os.Getenv("FRAG_ENV") == "production" {
```

**Comment by kennygrant** [comment]
This is an OS level thing depends on your setup. You can set them in a service for something like upstart or systemd if you are running this as a service on your server (as  I recommend). How are your running it?

If you are running it locally on OS X say, you can set that variable directly before running the fragmenta program (or the server itself), by doing something like FRAG_ENV=development fragmenta, however normally locally you'd run it in dev mode locally (be sure to have the production db set up before trying this of course).

**Comment by RayFoss** [comment]
Got it. I was expecting to see this in some sort of config file.
