### ISSUE TITLE
Error when using fragment migrate

### ISSUE THREAD

**Issue by R3plic8** [fragmenta/fragmenta-cms#15]
Using a clean Ubuntu VM, I Have installed Postgresql and Go. The fragmenta new cms command compiles, Then when changing to the created site path using fragmenta server or migrate commands i get "bash: ./fragmenta: No such file or directory". any advice on what the issue may be?

**Comment by kennygrant** [comment]
Apologies for the delay in responding. 

./fragmenta tries to open a fragmenta binary in the current path. So if you use that command, and you don't have fragmenta in your current dir, it won't find it. If you have installed fragmenta, best to use:

fragmenta migrate

If you haven't installed it perhaps install with go get github.com/fragmenta/fragmenta

Please reopen if this doesn't fix your issue.
