### ISSUE TITLE
Swapping DB

### ISSUE THREAD

**Issue by SCKelemen** [fragmenta/fragmenta-cms#22]
Can you tell me if it's possible to use MongoDB, which is a NoSQL database? I can rewrite the code, I am simply just accessing if its possible to use a NoSQL db with this, and how difficult it would be...

**Comment by kennygrant** [comment]
Yes it should be possible as the records are relatively simple and it doesn't use joins much at present (I plan to later though). I was also thinking of looking at an adapter for boltdb. 

Joins would be your main issue, which you'd have to handle manually (things like tags joins).

**Comment by SCKelemen** [comment]
@kennygrant thanks for the reply. I tried using mongo for another project, and I think I'm going to leave mongo. I just think in relations and SQL, not documents and objects.
