### ISSUE TITLE
Security - Don't store the password

### ISSUE THREAD

**Issue by SCKelemen** [fragmenta/fragmenta-cms#23]
Is there any reason you store the users password? Although it is encrypted, you probably don't actually need to store this.

**Comment by kennygrant** [comment]
The password of admins is hashed with a one-way hash - bcrypt in this case (a standard way to store them). This allows authentication so that we can then authorise admins to edit pages etc. Without it we'd have to no way to edit pages.

**Comment by SCKelemen** [comment]
Okay, I saw the function. 
```
// EncryptPassword DEPRECATED  - renamed to HashPassword to be clearer
func EncryptPassword(pass string) (string, error) {
	fmt.Printf("Please use HashPassword instead, auth.EncryptPassword is deprecated")
	return HashPassword(pass)
}
```
