### ISSUE TITLE
Stuck on fresh installation of Fragmenta cms 

### ISSUE THREAD

**Issue by rahu431** [fragmenta/fragmenta-cms#25]
# Im a new be for golang development, using windows 10 and my go Lang configuration setup as per the below details.

C:\work>go env
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=c:\work
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
# set CGO_ENABLED=1
# I can run any go example projects in local.
# Installed fragmenta as instructed in http://fragmenta.eu/install

C:\work>go get -u github.com/fragmenta/fragmenta
then use
C:\work>fragmenta new cms testcms
Getting this below error when i run this above line, am not sure why its ask me like this, please correct me, where am wrong.
"17:50:01 You must create your project in $GOPATH/src"
tried in this location to C:\work\src>fragmenta new cms testcms but same above message.

**Comment by kennygrant** [comment]
Hi, I think you're running into this bug:

https://github.com/fragmenta/fragmenta/issues/10

**Comment by TheMangoTrain** [comment]
To anyone having trouble with this. If you get a message "You must create your project in $GOPATH/src" then first check if your $GOPATH is defined. This is seperate from plain old $PATH. Use "echo $GOPATH". If it comes up blank, then you need to deal with that first before exe'ing fragmenta. To set gopath, use: "export GOPATH=$(go env GOPATH)". Confirm with "echo $GOPATH". Worked for me.

**Comment by kennygrant** [comment]
@TheMangoTrain thanks for this. Now that gopath is implicit sometimes, I should set up a default if it is not set.

**Comment by kennygrant** [comment]
Should be fixed now on windows.
