### ISSUE TITLE
Required Go Version

### ISSUE THREAD

**Issue by ericmathison** [fragmenta/fragmenta-cms#29]
Thought I'd mention that it might be worth putting the required Go version on the installation page on https://fragmenta.eu/ or elsewhere. It took me a while to figure out why my installation was failing on Go 1.5.3

```
$ fragmenta new cms go/src/foocms
15:41:40 Fetching from url: github.com/fragmenta/fragmenta-cms
15:43:25 Error calling go get exit status 1
```

 Apparently the fragmenta command line tool was failing to retrieve this repository because of a reference to the "context" package which was added to Go in 1.7. For example:

```
$ go get github.com/fragmenta/fragmenta-cms
package context: unrecognized import path "context"
```

**Comment by kennygrant** [comment]
Good point, I'll add a note. I'm probably going to support just the latest version of Go at this stage I'm afraid, because there have been a few additional features like graceful shutdown and autocert support that I'd like to utilise.

**Comment by kennygrant** [comment]
Thanks, this is now done on the website, and will be on readme files soon.
