### ISSUE TITLE
Editing top menu

### ISSUE THREAD

**Issue by klud1** [fragmenta/fragmenta-cms#30]
It'd be nice if it was possible to rename and/or get rid of some elements in the top bar
![screenshot from 2017-04-03 01-35-32](https://cloud.githubusercontent.com/assets/13160093/24595567/abd930ee-1805-11e7-88a8-263d16c96720.png)

**Comment by kennygrant** [comment]
You can do this by editing the template found at src/app/views/header.html.got or in your theme templates.
