### ISSUE TITLE
It needs a basic tutorial

### ISSUE THREAD

**Issue by suxonca** [fragmenta/fragmenta-cms#31]
Please, I no have idea how to start after install it.

Please, I would like to know if it has multi lang support for templates?
How works the template manager ?
Can use it to make a multilanguage post app?

Thanks a lot, great work

**Comment by suxonca** [comment]
by the way there is a way to make plugings?

**Comment by kennygrant** [comment]
Thanks for the comment, it definitely does. 

Multilang support is simple, just use utf8 encoding for whatever language you like and it should just work, any problems report them here. 
Template manager, you have to specify the template in the view, I think that'd be a good start for the tutorial. I have just finished some major changes, so wanted to get them deployed and then start on a tutorial. If you have any thoughts on the major points you'd like to see cleared up in a getting started guide, please do post them here.

**Comment by kennygrant** [comment]
Going to close this one to put all discussion on #19 which is pretty much the same thing. Definitely need better introductory docs, I have been too busy to look at them.
