### ISSUE TITLE
fragmenta server results in "a:unable to compile assets error:open public/assets/scripts/app-9ad47a746ac7acfa883dafa4ae0db5721bcea629.min.js: The system cannot find the path specified."

### ISSUE THREAD

**Issue by AP-Nothize** [fragmenta/fragmenta-cms#32]
On a fresh installation of cms in Windows 10 with go 1.8:

fragmenta new cms xxx (project generated)
fragmenta migrate (the server role and development db was created)

Then.....run the following in bash shell:

$ fragmenta server
16:47:04
------
Fragmenta version: 1.5rc
------
16:47:04 Building server...
16:47:04 Running go fmt at ./...
16:47:05 Building server at d:\xxx\xxx\go\src\xxx\xxx/bin/fragmenta-server-local
16:47:06 Build completed successfully in 1.2570401s
16:47:06 Launching server...
2017-06-20:08:47:06 Starting server port:3000 [32m#info[0m
2017-06-20:08:47:06 Compiling Asssets [32m#info[0m
2017-06-20:08:47:06 a:unable to compile assets error:open public/assets/scripts/app-9ad47a746ac7acfa883dafa4ae0db5721bcea629.min.js: The system cannot find the path specified. [31m#fatal[0m

**Comment by AP-Nothize** [comment]
Manually creating public/assets/scripts folder then result in a harder error:

a:unable to compile assets error:Error marshalling assets file secrets/assets.json json: error calling MarshalJSON for type *assets.Collection: invalid character 'a' in string escape code [31m#fatal[0m

**Comment by AP-Nothize** [comment]
It turns out to be caused by the path separator \ is not propertly escaped in File.go........for Windows.

**Comment by kennygrant** [comment]
I'm afraid there are a few errors like this on windows that I have still to track down - pull requests welcome if you wish to get them fixed, I have limited time and resources to test on windows at the moment.

**Comment by rebootcode** [comment]
This happened on "Ubuntu 16.04" too just now.

**Comment by rebootcode** [comment]
Ok, This looks like permission error. I fixed it by creating folder and blank file name with provided file name on error with it and re-ran the command. Now the codes are populated inside the code and server started.

So, This could be `File Permission` error too.

@kennygrant  i think you should check if file exists or if it has permission to create file - else send out the error message.

**Comment by kennygrant** [comment]
Yes missing folder in the repo, sorry about that.

**Comment by rebootcode** [comment]
Yes, this issue can be closed by fixing it with missing folder and by creating the missing file inside the folder.
