### ISSUE TITLE
fragmenta: command not found

### ISSUE THREAD

**Issue by rebootcode** [fragmenta/fragmenta-cms#33]
I have go 1.8.3 in Ubuntu 16.04 and i ran 2 command below :-

`go get -u github.com/fragmenta/fragmenta`
then
`fragmenta new cms blog`

and i got the error `fragmenta: command not found`

**Comment by kennygrant** [comment]
So the fragmenta command is not in your path (either didn't build or your gopath/bin is not in your path). If you do echo $PATH what do you see?

**Comment by kennygrant** [comment]
Going to close this one in favour of the issue opened on the fragmenta tool.
