### ISSUE TITLE
Error copying project exec "cp"

### ISSUE THREAD

**Issue by justinpretorius** [fragmenta/fragmenta-cms#41]
Good day

I have an error I keep getting when trying to install on Windows 10.  The message I get is as follows:
16:34:10 Fetching from url: github.com/fragmenta/fragmenta-cms
16:34:15 Creating files at: C:\Users\username\go\src\github.com\username\mycms
16:34:15 Error copying project exec: "cp": executable file not found in %PATH%

Where is this cp.exe supposed to be?

**Comment by kennygrant** [comment]
Can you try again just now, this should be fixed now (it's a problem with the fragmenta tool on windows). If not fixed please do reopen or file again.
