### ISSUE TITLE
JS Error: sel is not defined

### ISSUE THREAD

**Issue by nanohard** [fragmenta/fragmenta-cms#45]
The following JS error occurs when editing a blog post or page.
Trying to align the text in left, right, and center alignment causes the error.
Tried selecting the text and also just having the cursor on the line when selecting the alignment.
```
editable.js:127 Uncaught ReferenceError: sel is not defined
at Object.cleanAlign (editable.js:127)
at HTMLAnchorElement.<anonymous> (editable.js:86)
```

**Comment by kennygrant** [comment]
Thanks, do you want to have a go at fixing? If so please do put in a pull request, if not I'll get it fixed soon.

**Comment by kennygrant** [comment]
Thanks for reporting, I don't use this function much so hadn't noticed it was broken after removing jquery, it was a little more involved than I hoped.
